### PR TITLE
Remove lmstat binary

### PR DESCRIPTION
**Pull request by julianaklulo**
#### What
Remove `lmstat` binary, adding two env vars to set the path to the binaries instead (`lmstat` and `rlmstat`).

#### Why
In order to make the project open source, we need to remove the proprietary binary that was being distributed with the agent.

`Task`: https://app.clickup.com/t/206e2mv

### CODE REVIEW

**Review by jamesbeedy — APPROVED** [review]
Nice! 👍

**Comment by dusktreader** [comment]
Please wait to merge this until after the staging releases this week.

**Comment by julianaklulo** [comment]
> Please wait to merge this until after the staging releases this week.

Then I think we'll need to copy the `rlmstat` binary (the same way we are doing with the `lmstat`) for the staging deploy tomorrow.

**Comment by heitorPB** [comment]
This change how we use the charm. We need to add binaries with the charm (via a custom config?) and set the env vars correctly.

**Pull request merged**
