### PR TITLE
changed the CORS policy to allow origins from everywhere

### PR DESCRIPTION
**Pull request by matheushent**
#### What
Please provide a short description of the purpose of this pull request.

#### Why
Explain why the proposed change is necessary.

`Task`: https://omnivector-solutions.monday.com/boards/XXXX/pulses/YYYY

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

### CODE REVIEW

**Comment by heitorPB** [comment]
Why this is needed?

**Comment by matheushent** [comment]
> Why this is needed?

To make the integration with the frontend to work. Basically, on k8s, the Ingress resource will control the access so the CORS policy is actually not needed.

**Comment by julianaklulo** [comment]
Will this have impact in the backend version that is currently deployed on lambda?

**Comment by matheushent** [comment]
> Will this have impact in the backend version that is currently deployed on lambda?

99% sure the answer is no. @dusktreader can you confirm?

**Review by jamesbeedy — APPROVED** [review]
👍

**Comment by jamesbeedy** [comment]
rebase on armada-mvp branch to resolve conflicts then I'm g2g!

**Pull request merged**
